### ISSUE TITLE
ui design

### ISSUE THREAD

**Issue by aeolyus** [EVSD/EVSD-SITE#51]
Someone should sketch out a basic design of what they want the website to be like.
And also thanks for copying my website design @bananabot1024

**Comment by varmichelle** [comment]
Todo list: (use ui3.0 as the base branch)
- [x] fix radio buttons (port this code: https://github.com/EVSD/EVSD-SITE/commit/dc1654279759bdfdead0ce6336e226dc5a814d15)
- [x] fix select inputs (for admins selecting users, selecting tournaments)
- [ ] fix date picker add add it to all date forms (it's not working in some pages like tournament creation, but it might be just my computer)
- [x] make buttons pretty 
- [x] login prettify (use ui branch)
- [x] fix footer so it's not floating; make sure it stays at bottom (port this code: https://github.com/EVSD/EVSD-SITE/commit/247692caf84b3cc45c9cd35a05a5ee919171e56a)
- [ ] fix the account balance display cards (accordion not working)
- [ ] fix sidenav dropdown (nothing happens when it's clicked even with script)
- [ ] add the homepage content from the previous repo and make it pretty
- [ ] make waivers display properly on profile (if this doesn't work just get rid of the waiver on user profile)
- [ ] button event clicks
- [ ] make tournament editing allow you to edit all tournaments created (if this has already been implemented, it's probably just my computer being stupid)
- [ ] make logout into a pretty button
- [ ] after finishing UI, make sure everything works as usual (log payments, creating tournaments, etc)
- [ ] add materialize icons in front of every input (similar to signup)
- [x] make radio buttons work on signup
- [ ] make choose file button on signup pretty
- [ ] make the info / about pages pretty
- [x] add other info pages

**Comment by jacksonchui** [comment]
plan to fix in #52

**Comment by jacksonchui** [comment]
https://github.com/EVSD/EVSD-SITE/commit/76f2695f8d12f19e39c504693ebf97c63b3ef6e0
